/**
 * File: layout.tsx
 * Project: next-layout-rfc-sample
 * File Created: 25 Oct 2022 09:41:55
 * Author: und3fined (me@und3fined.com)
 * -----
 * Last Modified: 25 Oct 2022 09:53:43
 * Modified By: und3fined (me@und3fined.com)
 * -----
 * Copyright (c) 2022 und3fined.com
 */
import Head from 'next/head';

import '../styles/globals.css';

type LayoutProps = {
  children: React.ReactNode;
};

export default function LayoutRoot({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='layout-rfc'>Layout RFC sample</div>
      <div>{children}</div>
    </>
  );
}
